[build]
  base = "client"
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[build.environment]
  MONGODB_URI = "mongodb+srv://janotorino:KMj8VFX6Lbfkhk5c@cluster0.vmhqfzj.mongodb.net/Portfolio?retryWrites=true&w=majority&appName=Cluster0"

# ✅ Redirect all API requests to Netlify functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# ✅ Redirect SPA routes to index.html (for React/Vite apps)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
