[build]
  base = "client"
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["mongodb"]

[build.environment]
  MONGODB_URI = "mongodb+srv://janotorino:KMj8VFX6Lbfkhk5c@cluster0.vmhqfzj.mongodb.net/Portfolio?retryWrites=true&w=majority&appName=Cluster0"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
